### PR TITLE
Added setSpeed to set wad speed during playback

### PR DESCRIPTION
**Pull request by torch2424**
This simply adds to the set____ functions, and is similar to the setPanning() function, however it will allow for setting the speed during playback!

This was tested using Flyxer (see here: https://github.com/julianpoy/Flyxer), and was working. It should allow for any wad's playback speed to be changed during playback. Any additional testing is much appreciated.

Thank You!

### CODE REVIEW

**Comment by rserota** [comment]
The code looks good, but Github is telling me there are conflicts. Maybe there's something small you can clean up on your end?

**Comment by torch2424** [comment]
Of course, I'll get on that, probably due to the last branch being pulled :)

**Comment by torch2424** [comment]
This is fixed and ready to go!

thank you @rserota !

**Comment by rserota** [comment]
Looks good. Thanks for contributing!

**Comment by torch2424** [comment]
@rserota You are welcome! Thank you for letting me be a part of this! Wad is super cool!

**Pull request merged**
